# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Solana MCP Server
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy source
COPY . .

# Fix syntax error in pumpfun.js by replacing unquoted identifier
RUN sed -i 's/params.rpcUrl || process.env.HELIUS_RPC_URL || your rpc url/params.rpcUrl || process.env.HELIUS_RPC_URL || ""/' src/pumpfun.js

EXPOSE 3000
CMD ["node", "src/mcp-server-new.js"]
